import { StyleSheet, Dimensions, Platform } from "react-native";

// Bottom safe-area padding — on iOS add extra spacing so content clears the home indicator
export const BOTTOM_INSET = Platform.OS === "ios" ? 34 : 0;

export const PURPLE = "#6334f5";
const { height: SCREEN_HEIGHT } = Dimensions.get("window");

export const styles = StyleSheet.create({
  // ── Widget overlay ──
  overlay: {
    ...StyleSheet.absoluteFillObject,
  } as const,
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
  } as const,
  widgetPanel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  container: {
    backgroundColor: "#fff",
    height: SCREEN_HEIGHT * 0.9,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: "hidden",
  },
  content: { flex: 1, padding: 24, display: "flex" },

  // ── Header ──
  headerWrapper: { marginBottom: 20 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerBackBtn: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  headerBackArrow: { fontSize: 22, color: "#111", fontWeight: "400" },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    color: "#111",
  },
  headerCloseBtn: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  headerCloseIcon: { fontSize: 18, color: "#333" },

  // ── Progress ──
  progressSection: { marginTop: 10 },
  stepText: { fontSize: 12, fontWeight: "600", color: "#555", marginBottom: 8 },
  progressSegments: { flexDirection: "row", height: 3 },
  progressSegment: { flex: 1, height: 3, borderRadius: 2 },
  progressSegmentActive: { backgroundColor: PURPLE },
  progressSegmentInactive: { backgroundColor: "#E0E0E0" },

  // ── Layout ──
  centerCol: { alignItems: "center", marginTop: 16 },
  spacer: { flex: 1 },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },

  // ── Typography ──
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111",
    marginBottom: 8,
    paddingHorizontal: 32,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    paddingHorizontal: 32,
    lineHeight: 20,
  },
  titleLeft: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111",
    marginBottom: 4,
  },
  subtitleLeft: { fontSize: 13, color: "#666", marginBottom: 24 },
  titleCenter: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111",
    marginBottom: 8,
    textAlign: "center",
  },
  subtitleCenter: { fontSize: 14, color: "#666", textAlign: "center" },

  // ── Logo / Icons ──
  logoCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#f2eeff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  logoCircleSmall: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#f2eeff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  assetIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  assetIconLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  walletWaitCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#f2eeff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },

  // ── Onboarding Card ──
  onboardingCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 16,
    padding: 16,
    borderColor: "#eee",
    borderWidth: 1,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111",
    marginBottom: 4,
  },
  cardSub: { fontSize: 12, color: "#666", marginBottom: 16, lineHeight: 18 },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: "#ccc",
    marginRight: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: { backgroundColor: PURPLE, borderColor: PURPLE },
  termsText: { flex: 1, fontSize: 12, color: "#555", lineHeight: 16 },
  termsLink: {
    color: PURPLE,
    fontWeight: "700",
    textDecorationLine: "underline",
  },

  // ── Buttons ──
  primaryBtn: {
    backgroundColor: PURPLE,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
  },
  primaryBtnDisabled: { backgroundColor: "#d1c4e9" },
  primaryBtnText: { color: "white", fontSize: 16, fontWeight: "600" },
  cancelLink: { alignItems: "center", paddingVertical: 12 },
  cancelText: { color: "#666", fontSize: 14, fontWeight: "500" },

  // ── Options / Wallet List ──
  optionsList: { marginTop: 8 },
  optionBtn: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 16,
    marginBottom: 12,
  },
  optionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f5f5f5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  optionTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#111",
    marginBottom: 2,
  },
  optionSub: { fontSize: 12, color: "#666" },
  arrow: { fontSize: 18, color: "#ccc" },
  walletOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 16,
    marginBottom: 12,
  },
  walletOptionSelected: { borderColor: PURPLE, backgroundColor: "#faf8ff" },
  walletName: { fontSize: 15, fontWeight: "600", color: "#111", flex: 1 },
  radioUnchecked: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#ccc",
  },
  radioChecked: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: PURPLE,
    alignItems: "center",
    justifyContent: "center",
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: PURPLE,
  },

  // ── Asset / Search ──
  pill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  pillText: { fontSize: 12, fontWeight: "600", color: "#111", marginLeft: 6 },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 16,
  },
  searchInput: { flex: 1, fontSize: 14, color: "#111" },
  assetRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  assetName: { fontSize: 15, fontWeight: "600", color: "#111" },
  assetSymbol: { fontSize: 12, color: "#666", marginTop: 2 },
  assetBalance: { fontSize: 15, fontWeight: "600", color: "#111" },

  // ── Amount Entry ──
  amountInputDisplay: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 24,
    marginBottom: 8,
  },
  amountText: { fontSize: 40, fontWeight: "700", color: "#111" },
  verticalDivider: {
    width: 2,
    height: 32,
    backgroundColor: "#eee",
    marginHorizontal: 12,
  },
  amountSymbol: { fontSize: 20, fontWeight: "600", color: "#666" },
  usdValue: { fontSize: 14, color: "#888", marginBottom: 24 },
  presetRow: { flexDirection: "row", gap: 12 },
  presetBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "#f5f5f5",
  },
  presetText: { fontSize: 13, fontWeight: "600", color: "#555" },
  numpad: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: -12,
    paddingHorizontal: 12,
  },
  numKey: {
    width: "30%",
    aspectRatio: 2,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderRadius: 8,
  },
  numText: { fontSize: 24, fontWeight: "500", color: "#111" },

  // ── Review ──
  reviewCard: {
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 16,
    padding: 16,
    marginTop: 24,
  },
  reviewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  reviewLabel: { fontSize: 14, color: "#666" },
  reviewValue: { fontSize: 14, fontWeight: "600", color: "#111" },
  infoBox: {
    flexDirection: "row",
    backgroundColor: "#f8f9fa",
    padding: 12,
    borderRadius: 12,
    marginTop: 16,
  },
  infoText: { flex: 1, fontSize: 12, color: "#666", lineHeight: 18 },

  // ── Status Steps ──
  statusList: { marginTop: 32, paddingHorizontal: 16 },
  statusRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  statusDotActive: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: PURPLE,
    marginTop: 4,
    marginRight: 16,
  },
  statusDotInactive: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#eee",
    marginTop: 4,
    marginRight: 16,
  },
  statusLine: {
    position: "absolute",
    left: 5,
    top: 16,
    bottom: 0,
    width: 2,
    backgroundColor: "#eee",
    zIndex: -1,
  },
  statusTitle: { fontSize: 14, fontWeight: "700", color: "#111" },
  statusSub: { fontSize: 12, color: "#666", marginTop: 2 },
  statusTitleInactive: { fontSize: 14, fontWeight: "500", color: "#999" },
  footerNote: {
    textAlign: "center",
    fontSize: 12,
    color: "#888",
    marginBottom: 16,
  },

  // ── Success ──
  successCheckOuter: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#d4f5d4",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  successCheckInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#22c55e",
    alignItems: "center",
    justifyContent: "center",
  },
  successStatusList: { marginTop: 20, paddingHorizontal: 16 },
  successDotSmall: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#c4b5fd",
    marginTop: 4,
    marginRight: 16,
  },
  successStatusLine: {
    width: 2,
    height: 16,
    backgroundColor: "#e9d5ff",
    marginLeft: 4,
    marginBottom: 4,
  },
  successAmountLarge: {
    fontSize: 36,
    fontWeight: "800",
    color: "#111",
    marginBottom: 4,
  },
  successDate: { fontSize: 13, color: "#666", marginBottom: 8 },
  txCard: {
    backgroundColor: "#f5f5f5",
    borderRadius: 14,
    padding: 16,
    marginTop: 4,
  },
  txLabel: {
    fontSize: 13,
    color: "#666",
    marginBottom: 4,
    fontWeight: "600",
    textAlign: "center",
  },
  txRow: { flexDirection: "row", alignItems: "center", marginTop: 6 },
  txIdTruncated: { flex: 1, fontSize: 13, fontWeight: "500", color: "#333" },
  explorerLink: { fontSize: 14, color: PURPLE, fontWeight: "600" },
});
